# اسم الملف: .github/workflows/kivy_android_build.yml (Attempt 1: Specific Build Tools Versions)

name: Build Android APK for WiFi Tester

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  build-android-apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Increase Swap Space
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 10

      - name: Set up Java JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Cache Buildozer and Pip packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.buildozer
            ~/.pip
            ~/.local/share/python-for-android
          key: ${{ runner.os }}-${{ hashFiles('buildozer.spec') }}-v2 # تغيير المفتاح لتحديث الكاش

      - name: Install system dependencies (Specific Versions)
        run: |
          sudo apt-get update
          # تثبيت أدوات البناء بإصدارات محددة
          sudo apt-get install -y --no-install-recommends \
            python3-pip \
            build-essential \
            git \
            m4 \
            pkg-config \
            expect \
            # تثبيت autoconf 2.69 و libtool 2.4.6 (إصدارات معروفة بالاستقرار)
            # هذه تتطلب إضافة مستودعات أقدم أو تثبيت يدوي
            # لكن في GitHub Actions، الأسهل هو محاولة تثبيتها مباشرة
            # إذا لم تكن متوفرة، سنضطر للبحث عن PPA أو تجميعها يدوياً
            autoconf=2.69-1 \ # هذا قد لا يكون متاحاً مباشرة في Noble
            automake=1:1.16.1-4 \ # هذا قد لا يكون متاحاً مباشرة في Noble
            libtool=2.4.6-15 \ # هذا قد لا يكون متاحاً مباشرة في Noble
            # إذا فشلت هذه، سنعود للنسخة العامة أو نبحث عن حل بديل
            
            # بقية الاعتماديات
            libsdl2-dev \
            libsdl2-image-dev \
            libsdl2-mixer-dev \
            libsdl2-ttf-dev \
            libportmidi-dev \
            libswscale-dev \
            libavformat-dev \
            libavcodec-dev \
            zlib1g-dev \
            libgstreamer1.0-dev \
            gstreamer1.0-plugins-base \
            gstreamer1.0-plugins-good
          
          # إذا فشلت الأوامر أعلاه، يمكن تجربة:
          # sudo apt-get install -y autoconf automake libtool # للتأكد من وجودها على الأقل
          
          sudo apt-get clean && sudo rm -rf /var/lib/apt/lists/*

      - name: Install Python dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install "cython<3.0"
          python3 -m pip install buildozer
          
          if [ ! -f requirements.txt ]; then
            echo "kivy" > requirements.txt
            echo "kivymd" >> requirements.txt
            echo "reportlab" >> requirements.txt
            echo "plyer" >> requirements.txt
            echo "pyjnius" >> requirements.txt
            echo "https://github.com/kivy-garden/graph/archive/master.zip" >> requirements.txt
          fi
          
          python3 -m pip install -r requirements.txt

      - name: Build APK with Buildozer (and auto-accept licenses)
        run: |
          yes | buildozer android debug

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: WiFi-Tester-APK
          path: bin/*.apk
          if-no-files-found: error
